# 端口
server:
  port: 9000

spring:
  application:
    # 应用名称
    name: impromptu-translate

# 翻译配置
translate:
  # 百度
  baidu:
    url: https://fanyi-api.baidu.com/api/trans/vip/translate
    app-id: 20230210001556554
    secret-key: BhqS8l61PhI08wc15M0K
  # 有道
  youdao:
    url: https://openapi.youdao.com/api
    app-id: 76ce008451753ad0
    secret-key: pckuQYYySTdYH1FmtqENmvcPk1BSJBs4